#!/usr/bin/env bash

export OTEL_SERVICE_NAME="openhands-cli"

## Log levels (not case-sensitive)
# _nameToLevel = {
#     'CRITICAL': CRITICAL,
#     'FATAL': FATAL,
#     'ERROR': ERROR,
#     'WARN': WARNING,
#     'WARNING': WARNING,
#     'INFO': INFO,
#     'DEBUG': DEBUG,
#     'NOTSET': NOTSET,
# }

poetry run opentelemetry-instrument --logs_exporter otlp --metrics_exporter none python -m openhands.cli.main --log-level warn
